/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAddContestRouteImport } from './routes/admin.add-contest'
import { Route as AdminAddProblemRouteImport } from './routes/admin.add-problem'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminContestsRouteImport } from './routes/admin.contests'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminProblemsRouteImport } from './routes/admin.problems'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ContestsSlugRouteImport } from './routes/contests.$slug'
import { Route as PointsHistoryRouteImport } from './routes/points.history'
import { Route as ProblemsIndexRouteImport } from './routes/problems.index'
import { Route as ProblemsIdRouteImport } from './routes/problems.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAddContestRoute = AdminAddContestRouteImport.update({
  id: '/add-contest',
  path: '/add-contest',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAddProblemRoute = AdminAddProblemRouteImport.update({
  id: '/add-problem',
  path: '/add-problem',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContestsRoute = AdminContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemsRoute = AdminProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsSlugRoute = ContestsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ContestsRoute,
} as any)
const PointsHistoryRoute = PointsHistoryRouteImport.update({
  id: '/points/history',
  path: '/points/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProblemsRoute,
} as any)
const ProblemsIdRoute = ProblemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProblemsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contests': typeof ContestsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/add-contest': typeof AdminAddContestRoute
  '/admin/add-problem': typeof AdminAddProblemRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/contests': typeof AdminContestsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/problems': typeof AdminProblemsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/contests/$slug': typeof ContestsSlugRoute
  '/points/history': typeof PointsHistoryRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/problems/': typeof ProblemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contests': typeof ContestsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/add-contest': typeof AdminAddContestRoute
  '/admin/add-problem': typeof AdminAddProblemRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/contests': typeof AdminContestsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/problems': typeof AdminProblemsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/contests/$slug': typeof ContestsSlugRoute
  '/points/history': typeof PointsHistoryRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/admin': typeof AdminIndexRoute
  '/problems': typeof ProblemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contests': typeof ContestsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/add-contest': typeof AdminAddContestRoute
  '/admin/add-problem': typeof AdminAddProblemRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/contests': typeof AdminContestsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/problems': typeof AdminProblemsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/contests/$slug': typeof ContestsSlugRoute
  '/points/history': typeof PointsHistoryRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/problems/': typeof ProblemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contests'
    | '/dashboard'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/problems'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/admin/add-contest'
    | '/admin/add-problem'
    | '/admin/analytics'
    | '/admin/contests'
    | '/admin/logs'
    | '/admin/problems'
    | '/admin/users'
    | '/auth/callback'
    | '/contests/$slug'
    | '/points/history'
    | '/problems/$id'
    | '/admin/'
    | '/problems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contests'
    | '/dashboard'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/admin/add-contest'
    | '/admin/add-problem'
    | '/admin/analytics'
    | '/admin/contests'
    | '/admin/logs'
    | '/admin/problems'
    | '/admin/users'
    | '/auth/callback'
    | '/contests/$slug'
    | '/points/history'
    | '/problems/$id'
    | '/admin'
    | '/problems'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contests'
    | '/dashboard'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/problems'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/admin/add-contest'
    | '/admin/add-problem'
    | '/admin/analytics'
    | '/admin/contests'
    | '/admin/logs'
    | '/admin/problems'
    | '/admin/users'
    | '/auth/callback'
    | '/contests/$slug'
    | '/points/history'
    | '/problems/$id'
    | '/admin/'
    | '/problems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContestsRoute: typeof ContestsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ProblemsRoute: typeof ProblemsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PointsHistoryRoute: typeof PointsHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/add-contest': {
      id: '/admin/add-contest'
      path: '/add-contest'
      fullPath: '/admin/add-contest'
      preLoaderRoute: typeof AdminAddContestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/add-problem': {
      id: '/admin/add-problem'
      path: '/add-problem'
      fullPath: '/admin/add-problem'
      preLoaderRoute: typeof AdminAddProblemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contests': {
      id: '/admin/contests'
      path: '/contests'
      fullPath: '/admin/contests'
      preLoaderRoute: typeof AdminContestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/problems': {
      id: '/admin/problems'
      path: '/problems'
      fullPath: '/admin/problems'
      preLoaderRoute: typeof AdminProblemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests/$slug': {
      id: '/contests/$slug'
      path: '/$slug'
      fullPath: '/contests/$slug'
      preLoaderRoute: typeof ContestsSlugRouteImport
      parentRoute: typeof ContestsRoute
    }
    '/points/history': {
      id: '/points/history'
      path: '/points/history'
      fullPath: '/points/history'
      preLoaderRoute: typeof PointsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof ProblemsRoute
    }
    '/problems/$id': {
      id: '/problems/$id'
      path: '/$id'
      fullPath: '/problems/$id'
      preLoaderRoute: typeof ProblemsIdRouteImport
      parentRoute: typeof ProblemsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAddContestRoute: typeof AdminAddContestRoute
  AdminAddProblemRoute: typeof AdminAddProblemRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminContestsRoute: typeof AdminContestsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminProblemsRoute: typeof AdminProblemsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAddContestRoute: AdminAddContestRoute,
  AdminAddProblemRoute: AdminAddProblemRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminContestsRoute: AdminContestsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminProblemsRoute: AdminProblemsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ContestsRouteChildren {
  ContestsSlugRoute: typeof ContestsSlugRoute
}

const ContestsRouteChildren: ContestsRouteChildren = {
  ContestsSlugRoute: ContestsSlugRoute,
}

const ContestsRouteWithChildren = ContestsRoute._addFileChildren(
  ContestsRouteChildren,
)

interface ProblemsRouteChildren {
  ProblemsIdRoute: typeof ProblemsIdRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
}

const ProblemsRouteChildren: ProblemsRouteChildren = {
  ProblemsIdRoute: ProblemsIdRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
}

const ProblemsRouteWithChildren = ProblemsRoute._addFileChildren(
  ProblemsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContestsRoute: ContestsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ProblemsRoute: ProblemsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PointsHistoryRoute: PointsHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
